sources = *.c /home/weihuan/C/Datastruct/Stack/Stack.c
target = bitree
CC = gcc
CCFLAG = -g -Wall -fsanitize=address -fno-omit-frame-pointer

all:
	$(CC) $(CCFLAG) $(sources) -o $(target)

clean:
	rm -f $(target)